---
title: "About Me"
page-layout: article
---

Below is an overview of my educational background, experience, and professional service. 

## Education
- Ph.D. Operations Research, *Air Force Institute of Technology*, Jan. 2023 – Mar. 2026
- M.S. Industrial and Human Factors Engineering, *Wright State University*, Aug. 2019 - Dec. 2021
- B.S. Industrial and Systems Engineering, *Wright State University*, Aug. 2017 - May 2021

## Experience
- Computer Engineer, *Air Force Research Laboratory*, Jan. 2025 - present
- Associate Computer Engineer, *Air Force Research Laboratory*, Feb. 2023 - Jan. 2025
- Research Engineer, *Applied Research Solutions*, Apr. 2022 - Feb. 2023
- Graduate Research Assistant, *Wright State University*, May 2021 - Dec. 2021
- Research Engineer Intern, *Applied Research Solutions*, May 2020 - Mar. 2022

## Professional Service & Membership

|Position|Organization|
|--------|------------|
|President|Cincinnati-Dayton INFORMS Chapter|
|Editorial Board Member|*OR/MS Tomorrow* (Student-led magazine of INFORMS)|
|Secretary-Treasurer|Tau Beta Pi Dayton Alumni Chapter|
|Advisor|Tau Beta Pi Ohio Eta Chapter (Air Force Institute of Technology)|
|Advisor|Tau Beta Pi Ohio Mu Chapter (Wright State University)|
|Director of Communications|TechFest Dayton Foundation|
|Exhibitors Coordinator|TechFest Dayton Steering Committee|
|Member|Wright State University Biomedical, Industrial and Human Factors Engineering Department's External Advisory Board|
|Member|Milton-Union Miami Valley Career Technical Center STEM Advisory Board|
|Member|Women in Defense|
|Member|Society of Women Engineers|

## Peer Review Service

### Journals
- Industrial & Systems Engineering Review, *Editorial Review Board Member*
- International Journal of ELectronics Engineering & Education, *ad hoc*
- Knowledge-based Systems, *ad hoc*
- Technology Information and Management, *ad hoc*

### Conferences
- Hawaii International Conference on System Sciences (HICSS), *ad hoc*
- IEEE National Aerospace and Electronics Conference (NAECON), *ad hoc*