---
title: "Service"
format: html
---

I am committed to advancing my profession and community through active service and leadership. My involvement spans professional societies, outreach initiatives, and advisory roles to advance the growth of science, technology, engineering, and mathematics (STEM) disciplines. Below are my active roles for 2025 - 2026.

## Professional Service

::: {.panel-tabset}

### Current Positions

|Position|Organization|
|--------|------------|
|President|Cincinnati-Dayton INFORMS Chapter|
|Editorial Board Member|*OR/MS Tomorrow* (Student-led magazine of INFORMS)|
|Secretary-Treasurer|Tau Beta Pi Dayton Alumni Chapter|
|Advisor|Tau Beta Pi Ohio Eta Chapter (Air Force Institute of Technology)|
|Advisor|Tau Beta Pi Ohio Mu Chapter (Wright State University)|
|Director of Communications|TechFest Dayton Foundation|
|Exhibitors Coordinator|TechFest Dayton Steering Committee|
|Member|Wright State University Biomedical, Industrial and Human Factors Engineering Department's External Advisory Board|
|Member|Milton-Union Miami Valley Career Technical Center STEM Advisory Board|

### Previous Positions

|Term|Position|Organization|
|----|--------|------------|
|2024-2026|Treasurer|Tau Beta Pi Ohio Eta Chapter (Air Force Institute of Technology)|
|2024-2026|Member|Tau Beta Pi Ohio Eta Chapter (AFIT) Best Thesis Committee|
|2024-2026|President| Tau Beta Pi Dayton Alumni Chapter|
|2024-2025|Treasurer|Cincinnati-Dayton INFORMS Chapter|
|2024-2025|Division Liaison|AFRL Sensors Directorate Junior Force Council|
|2024-2025|Advisor|Tau Beta Pi Student Advisory Board|
|2024-2025|Secretary|Society of Women Engineers South Ohio Section|
|2024|Secretary-Treasurer|Tau Beta Pi Ohio Eta Chapter (AFIT)|
|2023-2025|Lead/Co-lead Editor| *OR/MS Tomorrow* (Student-led magazine of INFORMS)|
|2023-2024|Secretary|Tau Beta Pi Ohio Eta Chapter (AFIT)|
|2023-2024|Board Member|IISE Dayton-Cincinnnati Chapter|
|2023-2024|Member|Tau Beta Pi Student Advisory Board|
|2022-2023|Vice Chair|Tau Beta Pi Student Advisory Board|
|2022| All-Ohio Activities Lead|IISE Dayton-Cincinnati Chapter|
|2021-2023|Social Media Coordinator|*OR/MS Tomorrow* (Student-led magazine of INFORMS)|
|2021-2022|Outreach Committee Chair|Tau Beta Pi Student Advisory Board|
|2021-2022|Board Member|IISE Student Leadership Board|

:::

## Journal/Conference Service

Chair:

- INFORMS Cincinnati-Dayton Symposium 2024

Reviewer:

- IEEE National Aerospace and Electronics Conference (NAECON)
- Hawaii International Conference on System Sciences (HICSS)